const FETCH_POPULAR_LIST_STARTED = "FETCH_POPULAR_LIST_STARTED";
const FETCH_POPULAR_LIST_ERROR = "FETCH_POPULAR_LIST_ERROR";
const FETCH_POPULAR_LIST_SUCCESS = "FETCH_POPULAR_LIST_SUCCESS";

const FETCH_TOP_RATED_LIST_STARTED = "FETCH_TOP_RATED_LIST_STARTED";
const FETCH_TOP_RATED_LIST_ERROR = "FETCH_TOP_RATED_LIST_ERROR";
const FETCH_TOP_RATED_LIST_SUCCESS = "FETCH_TOP_RATED_LIST_SUCCESS";

const FETCH_MOVIE_DETAIL_STARTED = "FETCH_MOVIE_DETAIL_STARTED";
const FETCH_MOVIE_DETAIL_ERROR = "FETCH_MOVIE_DETAIL_ERROR";
const FETCH_MOVIE_DETAIL_SUCCESS = "FETCH_MOVIE_DETAIL_SUCCESS";

const FETCH_MOVIE_VIDEOS_STARTED = "FETCH_MOVIE_VIDEOS_STARTED";
const FETCH_MOVIE_VIDEOS_ERROR = "FETCH_MOVIE_VIDEOS_ERROR";
const FETCH_MOVIE_VIDEOS_SUCCESS = "FETCH_MOVIE_VIDEOS_SUCCESS";

const STORE_MOVIE_LIST_PATH = "STORE_MOVIE_LIST_PATH";
const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
const TOGGLE_MENU = "TOGGLE_MENU";

module.exports = {
  FETCH_POPULAR_LIST_STARTED,
  FETCH_POPULAR_LIST_ERROR,
  FETCH_POPULAR_LIST_SUCCESS,
  
  FETCH_TOP_RATED_LIST_STARTED,
  FETCH_TOP_RATED_LIST_ERROR,
  FETCH_TOP_RATED_LIST_SUCCESS,
  
  FETCH_MOVIE_DETAIL_STARTED,
  FETCH_MOVIE_DETAIL_ERROR,
  FETCH_MOVIE_DETAIL_SUCCESS,
  
  FETCH_MOVIE_VIDEOS_STARTED,
  FETCH_MOVIE_VIDEOS_ERROR,
  FETCH_MOVIE_VIDEOS_SUCCESS,

  STORE_MOVIE_LIST_PATH,
  ADD_TO_FAVORITES,
  REMOVE_FROM_FAVORITES,
  TOGGLE_MENU,
}
